apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-agent-flow
  namespace: grafana-agent-flow
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana-agent
      version: ">=0.14.0 <1.0.0"
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: grafana-charts
      interval: 5m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    # https://github.com/grafana/agent/tree/main/operations/helm/charts/grafana-agent
    agent:
      # -- Mode to run Grafana Agent in. Can be "flow" or "static".
      mode: 'flow'
