apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tempo
  namespace: tempo
spec:
  interval: 15m
  chart:
    spec:
      chart: tempo-vulture
      version: 0.2.3
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: grafana-charts
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  # https://github.com/grafana/helm-charts/blob/main/charts/tempo-vulture/values.yaml
  values:
