apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opstesting
resources:
- testpod-wi-secretproviderclass.yaml
- ../../base/opstesting
patches:
- path: testpod-wi-serviceaccount.yaml
