# Docs
# Step 5. https://learn.microsoft.com/en-us/azure/aks/csi-secrets-store-identity-access
#
# https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/configurations/identity-access-modes/workload-identity-mode/
#
# kubectl get secretproviderclasses.secrets-store.csi.x-k8s.io -A
# kubectl get secretproviderclass testpod-wi-kv -n opstesting -o yaml
#
# NAMESPACE   NAME      AGE
# loki        loki-kv   12s
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  # name needs to be unique per namespace
  name: testpod-wi-kv
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"          
    tenantId: "blah" # The tenant ID of the key vault
    clientID: "47708379-cbb0-4745-9bae-c8b653b21af8" # Setting this to use workload identity    
    keyvaultName: "opsstackidmzweutestakskv"         # Set to the name of your key vault
    cloudName: ""                                    # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: testpod-wi-secrets-sa
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty

