apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
resources:
  - ../../base/ingress-nginx
patches:
  - path: namespace-patch.yaml
  - path: ingress-nginx-patch.yaml
  