apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana
resources:
  - namespace.yaml
  - release.yaml
  - network-policies.yaml
configMapGenerator:
  - name: dev-container-monitoring-cfg.v13
    files:
      - dev-container-monitoring.json=./dashboards/dev-container-monitoring.json
      - dev-linux-exporter.json=./dashboards/dev-linux-exporter.json
      - dev-windows-exporter-14451.json=./dashboards/dev-windows-exporter-14451.json
    options:
        disableNameSuffixHash: true