apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-agent-static-k8s
  namespace: grafana-agent-static-k8s
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana-agent-operator
      version: ">=0.2.15 <1.0.0"
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: grafana-charts
      interval: 5m
  values:
    # https://github.com/grafana/helm-charts/blob/main/charts/agent-operator/README.md
