apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus
resources:
  - ../../base/kube-prometheus-stack
  - ingress.yaml
patches:
- path: kube-prometheus-stack-values.yaml

