apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-mimir
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: apps-grafana
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps-mimir/test-azure-apps
  prune: true
  wait: true
  timeout: 5m0s
  decryption:
    provider: sops
  # https://fluxcd.io/flux/components/kustomize/kustomization/
  # Note: If you want to avoid var substitutions in scripts embedded in ConfigMaps or container commands, you must use 
  # the format $var instead of ${var}. If you want to keep the curly braces you can use $${var} which will print out ${var}.
  postBuild:
    substitute:
      K_MIMIR_DNS_NAME: "mimir"
      K_LOKI_DNS_NAME: "loki"
      K_TEMPO_DNS_NAME: "tempo"
      K_PROMETHEUS_LOKI_DNS_NAME: prometheus-loki

