apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-tempo
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: apps-mimir
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps-tempo/test-azure-apps
  prune: true
  wait: true
  timeout: 5m0s
  decryption:
    provider: sops
  postBuild:
    substitute:
      K_MIMIR_DNS_NAME: "mimir"
      K_LOKI_DNS_NAME: "loki"
      K_PROMETHEUS_LOKI_DNS_NAME: prometheus-loki
      K_TEMPO_DNS_NAME: "tempo"
      K_TRACE_DNS_NAME: "trace"

