---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: sops-decryptor
  namespace: flux-system
spec:
  # note if you rebuild the MI the client id might be cached in your portal view
  clientID: ${K_SOPS_CLIENT_ID}
  resourceID: ${K_SOPS_RESOURCE_ID}
  type: 0  # user-managed identity
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: sops-decryptor-binding
  namespace: flux-system
spec:
  azureIdentity: sops-decryptor
  selector: sops-decryptor
