---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: grafana-azure-identity
  namespace: flux-system
spec:
  # note if you rebuild the MI the client id might be cached in your portal view
  clientID: ${K_GF_AZURE_MONITOR_CLIENT_ID}
  resourceID: ${K_GF_AZURE_MONITOR_RESOURCE_ID}
  type: 0  # user-managed identity
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: grafana-azure-identity-binding
  namespace: flux-system
spec:
  azureIdentity: grafana-azure-identity
  selector: grafana-azure-identity
---
