apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-controller
  namespace: flux-system
spec:
  selector:
    matchLabels:
      app: kustomize-controller
  template:
    metadata:
      labels:
        ## For aad-pod-identity
        # aadpodidbinding: ${IDENTITY_NAME} match the AzureIdentity name
        aadpodidbinding: sops-decryptor
    spec:
      containers:
      - name: manager
        ## For aad-pod-identity
        env:
        - name: AZURE_AUTH_METHOD
          value: msi
